export const products = [
  {
    id: "mini-creme-crossbody",
    name: "Mini Crème Crossbody",
    price: 920,
    category: "crossbody",
    image: "/images/Crossbody2.jpg",
    material: "Calfskin Leather",
    origin: "Italy",
    series: "Crossbody Classic",
    description: "The Mini Crème Crossbody is a masterclass in minimalist luxury. Handcrafted from premium calfskin leather, this piece features a structural silhouette that transitions seamlessly from day to evening."
  },
  {
    id: "summer-woven-tote",
    name: "Summer Woven Tote",
    price: 1850,
    category: "underarm",
    image: "/images/summer.jpg",
    material: "Natural Straw",
    origin: "Spain",
    series: "Natural Straw",
    description: "An exquisite woven companion designed for longevity and timeless appeal. Perfect for summer escapes."
  },
  {
    id: "Crossbody2",
    name: "Geneva Croc Trio",
    price: 18500,
    category: "limited",
    image: "/images/Crossbody2.jpg",
    material: "Patent Croc-Embossed Leather",
    origin: "Switzerland",
    series: "Executive Suite",
    description: "The Geneva Trio is the ultimate statement in functional opulence. This coordinated set features a grand structured satchel, a matching envelope clutch, and a compact card wallet, all finished in high-shine patent croc-emboss with polished gold-tone hardware."
  },
  {
    id: "Purse3",
    name: "Luna Dome Micro",
    price: 26,
    category: "purse",
    image: "/images/purse1.jpg",
    material: "Pebbled Vegan Leather",
    origin: "Italy",
    series: "Moonlight Series",
    description: "The Luna Dome Micro is an architectural statement in a compact form. Crafted from high-durability pebbled leather, it features a dual top-handle design and a detachable silver bijoux chain strap for effortless versatility."
  },
  {
    id: "Purse2",
    name: "Aurora Geometric Satchel",
    price: 35,
    category: "purse",
    image: "/images/purse2.jpg", 
    material: "Croc-Embossed Vegan Leather",
    origin: "Spain",
    series: "Geometrica Heritage",
    description: "A masterclass in bold geometry, the Aurora features a striking triangular envelope flap secured by a single gold pyramid stud. The contrasting croc-embossed side panels provide a high-fashion architectural silhouette, available in a curated palette of vibrant seasonal hues."
  },
  {
    id: "heritage-2in1-set",
    name: "Heritage Pouch Satchel",
    price: 1950,
    category: "handbag",
    image: "/images/underarms.jpg",
    material: "Pebbled Vegan Leather",
    origin: "Italy",
    series: "Executive",
    description: "A professional duo featuring a structured multi-tone satchel with a gold-tone rotary clasp and a matching standalone zip pouch."
  },
  {
    id: "mosaic-panel-tote",
    name: "Mosaic Patchwork Underarm",
    price: 1680,
    category: "handbag",
    image: "/images/underarms2.jpg",
    material: "Suede & Smooth Leather Blend",
    origin: "Spain",
    series: "Urban Geometry",
    description: "A trendy rectangular silhouette defined by unique patchwork paneling and a hardware-free, minimalist aesthetic."
  },
  {
    id: "chroma-curve-mini",
    name: "Chroma Curve Satchel",
    price: 1420,
    category: "handbag",
    image: "/images/underarms3.jpg",
    material: "Textured Saffiano Leather",
    origin: "France",
    series: "Spectrum Series",
    description: "A petite top-handle satchel with a curved flap and signature teardrop gold clasp. Available in a curated professional palette."
  },
  {
    id: "quilted-valet-tote",
    name: "Quilted Valet Tote",
    price: 1750,
    category: "handbag",
    image: "/images/underarms4.jpg",
    material: "High-Density Quilted PU",
    origin: "Italy",
    series: "Diamond Series",
    description: "Classic diamond quilting meets modern utility. Includes a matching card valet attached by a delicate gold-tone chain."
  },
  {
    id: "pearl-aria-bucket",
    name: "Pearl Aria Bucket Bag",
    price: 1580,
    category: "handbag",
    image: "/images/underarms5.jpg",
    material: "Smooth Synthetic Leather",
    origin: "Italy",
    series: "Elegance Series",
    description: "A unique bucket silhouette elevated by a signature oversized pearl handle and a floral-embossed center clasp."
  },
  {
    id: "ribbed-cloud-hobo",
    name: "Ribbed Cloud Underarm",
    price: 1350,
    category: "handbag",
    image: "/images/underarms6.jpg",
    material: "Pleated Vegan Leather",
    origin: "South Korea",
    series: "Texture Series",
    description: "Featuring a distinct vertical ribbed texture and a soft 'cloud' scrunchie handle. A lightweight, tactile statement piece."
  },
  {
    id: "coastal-straw-set-01",
    name: "Coastal Breeze Set",
    price: 1100,
    category: "picnic",
    image: "/images/summer.jpg",
    material: "Hand-Woven Paper Straw",
    origin: "Italy",
    series: "Riviera",
    description: "A coordinated sun-ready duo. This matching set features a structured straw tote with tan leather handles and a wide-brimmed hat accented with elegant earthy stripes."
  },
  {
    id: "monogram-tote-01",
    name: "Signature Alpha Tote",
    price: 950,
    category: "picnic",
    image: "/images/summer2.jpg",
    material: "Heavy-Duty Cotton Canvas",
    origin: "France",
    series: "Personalized",
    description: "A bold, monochrome statement piece. This structured canvas tote features a prominent monogram aesthetic, contrast black trim, and a charming striped ribbon accent."
  },
  {
    id: "nautical-striped-set-01",
    name: "Nautical Horizon Set",
    price: 1250,
    category: "picnic",
    image: "/images/summer3.jpg",
    material: "Reinforced Raffia",
    origin: "Spain",
    series: "Riviera",
    description: "Deep navy nautical stripes define this premium summer set. Designed for high-end picnics and coastal escapes, blending durability with a timeless maritime look."
  },
  {
    id: "lace-detail-set-01",
    name: "Lace Overlay Straw Set",
    price: 1180,
    category: "picnic",
    image: "/images/summer4.jpg",
    material: "Straw with Lace Crochet",
    origin: "Greece",
    series: "Riviera",
    description: "An intricate twist on classic straw. This set features a delicate white lace crochet overlay on both the tote and the hat brim for a romantic, artisanal finish."
  },
  {
    id: "executive-tri-set-08",
    name: "Heritage Tri-Element Set",
    price: 2450,
    category: "underarm",
    image: "/images/underarms7.jpg",
    material: "Grained Vegan Leather & Antique Gold Hardware",
    origin: "Italy",
    series: "Executive Collection",
    description: "The ultimate professional toolkit. This 3-in-1 set includes a high-capacity structured tote with braided leather detailing, a matching continental envelope wallet, and a compact cylindrical tech/accessory pouch."
  },
  {
    id: "Underarm1",
    name: "Sienna Baguette",
    price: 24,
    category: "underarm",
    image: "/images/UnderarmsBag1.jpg",
    material: "Vegan Polished Leather",
    origin: "Italy",
    series: "City Nomad Series",
    description: "The Sienna Baguette captures a vintage silhouette with modern chocolate tones. Featuring a distinctive gold-plated push-lock and a knotted cord strap, it is the perfect companion for the urban minimalist."
  },
  {
    id: "Underarm2",
    name: "Colette Ribbon Clasp",
    price: 22,
    category: "underarm",
    image: "/images/UnderarmsBag2.jpg",
    material: "Smooth Nappa Finish",
    origin: "France",
    series: "Elysée Collection",
    description: "A vision in ivory, the Colette Ribbon Clasp defines feminine luxury. Its pristine rectangular structure is accented by a delicate gold-toned bow, offering a sophisticated edge to any contemporary ensemble."
  },
  {
    id: "Crossbody",
    name: "Valentina Pyramid Tote",
    price: 28,
    category: "underarm",
    image: "/images/Crossbody.jpg",
    material: "Croc-Embossed Vegan Leather",
    origin: "Spain",
    series: "Geometrica Edition",
    description: "Available in a spectrum of vibrant hues, the Valentina features a unique structured 'envelope' front with a signature gold pyramid stud. The croc-embossed side panels provide a high-texture contrast for the bold fashionista."
  },
  {
    id: "Purse5",
    name: "Hampton Slouch & Pouch",
    price: 42,
    category: "purse",
    image: "/images/bagandpurse.jpg",
    material: "Soft Grain Calfskin",
    origin: "Denmark",
    series: "Minimalist Travel Series",
    description: "The Hampton Slouch is designed for the modern woman who values both space and style. This oversized hobo bag features a soft, architectural drape and includes a coordinated zip pouch to keep your smaller essentials organized within its generous interior."
  },
  {
    id: "Purse3_Scarlet",
    name: "Scarlet Halo Clutch",
    price: 38,
    category: "purse",
    image: "/images/purse3.jpg",
    material: "Ultra-Smooth Matte Leather",
    origin: "Belgium",
    series: "Avant-Garde Series",
    description: "The Scarlet Halo is a wearable piece of art. Its vibrant red pillowy structure is contrasted by a massive, semi-circular gold hardware handle that defines the silhouette."
  },
  {
    id: "Crossbody_Cannes",
    name: "Cannes Striped Tote",
    price: 34,
    category: "purse",
    image: "/images/Crossbody3.jpg",
    material: "Woven Canvas & Vegan Leather Trim",
    origin: "France",
    series: "Riviera Resort Series",
    description: "Inspired by the coastal elegance of the French Riviera, the Cannes Striped Tote features a durable woven canvas body accented by high-contrast vertical stripes."
  },
];